-- ==============================================================================
-- Supabase Schema for Personal Website (Multi-User Isolated Version)
-- ==============================================================================
-- 说明: 
-- 1. 此脚本将创建带有 `user_id` 字段的表，确保数据归属于特定用户。
-- 2. 启用了 RLS (行级安全策略)，确保用户只能增删改查自己的数据。
-- 3. 如果表已存在，请先备份数据，或者手动执行 ALTER TABLE 添加 user_id 字段。
-- ==============================================================================

-- 1. Music Table (音乐)
create table if not exists public.music (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  title text not null,
  link text,
  cover text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tech Articles Table (技术文章)
create table if not exists public.tech_articles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  title text not null,
  summary text,
  content text,
  tags text[],
  date text,
  "iconName" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Ideas Table (灵感)
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  title text not null,
  description text,
  content text,
  "references" text,
  stage text,
  tags text[],
  date text,
  priority text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Trips Table (旅行)
create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  location text,
  title text,
  date text,
  "imageColor" text,
  description text,
  content text,
  height text,
  coordinates jsonb,
  "imageUrl" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Sports Records Table (运动记录)
create table if not exists public.sports_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  date text,
  type text,
  name text,
  distance text,
  time text,
  pace text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Books Table (阅读)
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  title text not null,
  author text,
  rating numeric,
  status text,
  progress numeric,
  date text,
  quote text,
  review text,
  notes jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Resources Table (资源分享)
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- 核心隔离字段
  title text not null,
  type text,
  category text,
  description text,
  link text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- Row Level Security (RLS) Setup
-- ==============================================================================

-- Enable RLS on all tables
alter table public.music enable row level security;
alter table public.tech_articles enable row level security;
alter table public.ideas enable row level security;
alter table public.trips enable row level security;
alter table public.sports_records enable row level security;
alter table public.books enable row level security;
alter table public.resources enable row level security;

-- ==============================================================================
-- Policies (Strict User Isolation)
-- 策略说明: 只允许用户操作 (Select, Insert, Update, Delete) 自己的数据 (auth.uid() = user_id)
-- ==============================================================================

-- 1. Music Policies
create policy "Users can view their own music" on public.music for select using (auth.uid() = user_id);
create policy "Users can insert their own music" on public.music for insert with check (auth.uid() = user_id);
create policy "Users can update their own music" on public.music for update using (auth.uid() = user_id);
create policy "Users can delete their own music" on public.music for delete using (auth.uid() = user_id);

-- 2. Tech Articles Policies
create policy "Users can view their own articles" on public.tech_articles for select using (auth.uid() = user_id);
create policy "Users can insert their own articles" on public.tech_articles for insert with check (auth.uid() = user_id);
create policy "Users can update their own articles" on public.tech_articles for update using (auth.uid() = user_id);
create policy "Users can delete their own articles" on public.tech_articles for delete using (auth.uid() = user_id);

-- 3. Ideas Policies
create policy "Users can view their own ideas" on public.ideas for select using (auth.uid() = user_id);
create policy "Users can insert their own ideas" on public.ideas for insert with check (auth.uid() = user_id);
create policy "Users can update their own ideas" on public.ideas for update using (auth.uid() = user_id);
create policy "Users can delete their own ideas" on public.ideas for delete using (auth.uid() = user_id);

-- 4. Trips Policies
create policy "Users can view their own trips" on public.trips for select using (auth.uid() = user_id);
create policy "Users can insert their own trips" on public.trips for insert with check (auth.uid() = user_id);
create policy "Users can update their own trips" on public.trips for update using (auth.uid() = user_id);
create policy "Users can delete their own trips" on public.trips for delete using (auth.uid() = user_id);

-- 5. Sports Records Policies
create policy "Users can view their own sports" on public.sports_records for select using (auth.uid() = user_id);
create policy "Users can insert their own sports" on public.sports_records for insert with check (auth.uid() = user_id);
create policy "Users can update their own sports" on public.sports_records for update using (auth.uid() = user_id);
create policy "Users can delete their own sports" on public.sports_records for delete using (auth.uid() = user_id);

-- 6. Books Policies
create policy "Users can view their own books" on public.books for select using (auth.uid() = user_id);
create policy "Users can insert their own books" on public.books for insert with check (auth.uid() = user_id);
create policy "Users can update their own books" on public.books for update using (auth.uid() = user_id);
create policy "Users can delete their own books" on public.books for delete using (auth.uid() = user_id);

-- 7. Resources Policies
create policy "Users can view their own resources" on public.resources for select using (auth.uid() = user_id);
create policy "Users can insert their own resources" on public.resources for insert with check (auth.uid() = user_id);
create policy "Users can update their own resources" on public.resources for update using (auth.uid() = user_id);
create policy "Users can delete their own resources" on public.resources for delete using (auth.uid() = user_id);
